### ISSUE TITLE
Optical Calculation with BSE gives an error

### ISSUE THREAD

**Issue by sblisesivdin** [sblisesivdin/gpaw-tools#83]
On a Windows 11 with WSL, Ubuntu 24.04 system.
gpaw-tools: Version information: v24.6.2b1
  uses GPAW 24.6.0, ASE 3.23.0 and PHONOPY 2.29.1

Optical Calculation example (Si-2atoms-optical) with BSE gives an error:

Traceback (most recent call last):
  File "/home/bora/gpaw-tools-main/gpawsolve.py", line 1872, in <module>
    struct = struct_from_file(inputfile = configpath, geometryfile = inFile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bora/gpaw-tools-main/gpawsolve.py", line 67, in struct_from_file
    inputf = __import__(Path(inputfile).stem, globals(), locals(), ['*'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Si-Step2-optical-BSE'

**Comment by sblisesivdin** [comment]
With GPAW 25.1.0 and gpaw-tools 25.2.1, BSE calculations can be done. However, directions are not working yet.
